### PR TITLE
Fix camera info

### PR DESCRIPTION
**Pull request by coxep**
Extensive updates to camera intrinsics. Backwards compatible with Astra mini devices.

---
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/13)

### CODE REVIEW

**Review by dandedrick — CHANGES_REQUESTED** [review]
Have these changes been submitted upstream? I'm assuming they would generally be useful and I've actually has orbbec merge changes I've requested recently. Getting these in upstream will back rebasing on their changes easier in the future and prevent conflict where someone else might make similar changes or make changes that effect the same lines of code.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/13#-:-LmBO3716NbR-AGcaLsT:b7ht3f0)* status: all files reviewed, 3 unresolved discussions (waiting on @bobhenz-jabil, @c-andy-martin, @coxep, and @howardcochran)

___
*[src/astra_driver.cpp, line 879 at r1](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/13#-LmBLHJb6Ow7gv26f2sK:-LmBLHJb6Ow7gv26f2sL:b4lgvgz) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/4ca34e3be1917e87a8e9b779b9925fe489a14a21/src/astra_driver.cpp#L879)):*
> ```cpp
> sensor_msgs::CameraInfoPtr AstraDriver::getColorCameraInfo(const AstraVideoMode& video_mode) const
> {
>     sensor_msgs::CameraInfoPtr info;
> ```

You added 2 spaces to the indentation to this whole function. This should be made consistent with the rest of the file, which is 2 space indentation. I think remaining consistent will help produce a better diff highlighting only what actually changed.
___
*[src/astra_driver.cpp, line 962 at r1](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/13#-LmBMFlI4dYkzVvZ5iBg:-LmBMFlI4dYkzVvZ5iBh:bprlk1w) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/4ca34e3be1917e87a8e9b779b9925fe489a14a21/src/astra_driver.cpp#L962)):*
> ```cpp
> sensor_msgs::CameraInfoPtr AstraDriver::getIRCameraInfo(const AstraVideoMode &video_mode) const
> {
> ```

This added whitespace is unneeded and this function has also modified the indentation level. This should also been switched back to 2 space indentation for consistency.
___
*[src/astra_driver.cpp, line 1053 at r1](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/13#-LmBMdNv5MsVjHOb_t_z:-LmBMdNv5MsVjHOb_ta-:b-vfdozp) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/4ca34e3be1917e87a8e9b779b9925fe489a14a21/src/astra_driver.cpp#L1053)):*
> ```cpp
> sensor_msgs::CameraInfoPtr AstraDriver::getDepthCameraInfo(const AstraVideoMode &video_mode) const
> {
>     sensor_msgs::CameraInfoPtr info(new sensor_msgs::CameraInfo);
> ```

This is another function that needs the indentation to be reset to match the files 2 space indent.

**Review by coxep — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/13)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @bobhenz-jabil, @c-andy-martin, @dandedrick, and @howardcochran)

___
*[src/astra_driver.cpp, line 879 at r1](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/13#-LmBLHJb6Ow7gv26f2sK:-LmBV0kb7SvHX6NwJvNM:bb6un1j) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/4ca34e3be1917e87a8e9b779b9925fe489a14a21/src/astra_driver.cpp#L879)):*
<details><summary><i>Previously, dandedrick (Dan Dedrick) wrote…</i></summary><blockquote>

You added 2 spaces to the indentation to this whole function. This should be made consistent with the rest of the file, which is 2 space indentation. I think remaining consistent will help produce a better diff highlighting only what actually changed.
</blockquote></details>

Done
___
*[src/astra_driver.cpp, line 962 at r1](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/13#-LmBMFlI4dYkzVvZ5iBg:-LmBV1psDgXpMb4E-PLB:bb6un1j) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/4ca34e3be1917e87a8e9b779b9925fe489a14a21/src/astra_driver.cpp#L962)):*
<details><summary><i>Previously, dandedrick (Dan Dedrick) wrote…</i></summary><blockquote>

This added whitespace is unneeded and this function has also modified the indentation level. This should also been switched back to 2 space indentation for consistency.
</blockquote></details>

Done
___
*[src/astra_driver.cpp, line 1053 at r1](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/13#-LmBMdNv5MsVjHOb_t_z:-LmBV4KA2eNp6HhIgu2R:bb6un1j) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/4ca34e3be1917e87a8e9b779b9925fe489a14a21/src/astra_driver.cpp#L1053)):*
<details><summary><i>Previously, dandedrick (Dan Dedrick) wrote…</i></summary><blockquote>

This is another function that needs the indentation to be reset to match the files 2 space indent.
</blockquote></details>

Done

**Review by coxep — COMMENTED** [review]
Agreed on all counts. Unfortunately, we need to get these changes for stereo S pose calibration. I will try to cherry pick this commit and upstream as well in near future

> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/13#-:-LmBedMl5MGCtCotoVEV:b-x0zol)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @bobhenz-jabil, @c-andy-martin, @dandedrick, and @howardcochran)

**Review by dandedrick — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bobhenz-jabil, @c-andy-martin, and @howardcochran)

**Pull request merged**
