### PR TITLE
Added reconfigurable video mode (RGB, IR)

### PR DESCRIPTION
**Pull request by coxep**
This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/1)

### CODE REVIEW

**Comment by c-andy-martin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[cfg/Astra.cfg, line 26 at r1](https://reviewable.io:443/reviews/badgertechnologies/ros_astra_camera/1#-L7_wauVa8IHflwGDHB6:-L7_wauVa8IHflwGDHB7:b-pxn23y) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/da6ba422e86fa896497558d3788f246026bb5342/cfg/Astra.cfg#L26)):*
> ```INI
> video_type_enum = gen.enum([  gen.const(  "RGB", int_t, 0,  "RGB video mode"),
>                               gen.const(  "IR", int_t, 1,  "IR video mode")],
>                               "output mode")
> ```

Maybe the description should be "video RGB/IR switch" or something like that. "output mode" is the same string as `output_mode_enum`

---

*[cfg/Astra.cfg, line 28 at r1](https://reviewable.io:443/reviews/badgertechnologies/ros_astra_camera/1#-L7_woYLhkpIgaz32azT:-L7_woYLhkpIgaz32azU:b97c2ep) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/da6ba422e86fa896497558d3788f246026bb5342/cfg/Astra.cfg#L28)):*
> ```INI
>                               "output mode")
> 
> gen.add("camera_override_mode", int_t, 0, "Override video type; 0=default, 1=IR", 0, 0, 1, edit_method = video_type_enum)
> ```

The text string has no RGB option. If RGB is default, maybe it should be `"Override video type; 0=RGB(default), 1=IR"` ?

---

*[include/astra_camera/astra_driver.h, line 167 at r1](https://reviewable.io:443/reviews/badgertechnologies/ros_astra_camera/1#-L7_xDn5zpHVH3RTXbcf:-L7_xDn5zpHVH3RTXbcg:bish202) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/da6ba422e86fa896497558d3788f246026bb5342/include/astra_camera/astra_driver.h#L167)):*
> ```objc
> 
>   int camera_override_mode_;
>   static const int RGB = 0;
> ```

even in a restricted namespace, these names are awful short and might cause a conflict. I would make them `CAMERA_OVERRIDE_MODE_RGB` and `CAMERA_OVERRIDE_MODE_IR`

---

*[src/astra_driver.cpp, line 402 at r1](https://reviewable.io:443/reviews/badgertechnologies/ros_astra_camera/1#-L7_yV2hDG7FklkaVSqp:-L7_yV2hDG7FklkaVSqq:b7sfjfk) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/da6ba422e86fa896497558d3788f246026bb5342/src/astra_driver.cpp#L402)):*
> ```cpp
>       if (camera_override_mode_ == IR)
>       {
>         // ROS_ERROR("Cannot stream RGB and IR at the same time. Streaming IR only.");
> ```

Remove this. Actually, I'd also consider removing the `return`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/badgertechnologies/ros_astra_camera/1)*

**Comment by c-andy-martin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/astra_driver.cpp, line 402 at r1](https://reviewable.io:443/reviews/badgertechnologies/ros_astra_camera/1#-L7_yV2hDG7FklkaVSqp:-L7a88J3CyMxXcVPjxMU:b-pwjcfu) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/da6ba422e86fa896497558d3788f246026bb5342/src/astra_driver.cpp#L402)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

Remove this. Actually, I'd also consider removing the `return`
</blockquote></details>

and simplifying logic, didn't finish my above statement. I can't finish the review this moment, I'll look at it more later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/badgertechnologies/ros_astra_camera/1)*

**Comment by c-andy-martin** [comment]
*[include/astra_camera/astra_driver.h, line 167 at r1](https://reviewable.io:443/reviews/badgertechnologies/ros_astra_camera/1#-L7_xDn5zpHVH3RTXbcf:-L7aH0ShXk45rCtWTmMw:britw8) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/da6ba422e86fa896497558d3788f246026bb5342/include/astra_camera/astra_driver.h#L167)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

even in a restricted namespace, these names are awful short and might cause a conflict. I would make them `CAMERA_OVERRIDE_MODE_RGB` and `CAMERA_OVERRIDE_MODE_IR`
</blockquote></details>

I can really go either way on this one, actually. Up to you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/badgertechnologies/ros_astra_camera/1)*

**Comment by c-andy-martin** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/astra_driver.cpp, line 474 at r2](https://reviewable.io:443/reviews/badgertechnologies/ros_astra_camera/1#-L7aG43fErHWT7DdCsI3:-L7aG43fErHWT7DdCsI4:b-u3f2qk) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/874ec41afe4328d25ac3e8eced4de7b0c674612c/src/astra_driver.cpp#L474)):*
> ```cpp
>       if (preferred_camera_mode_ == RGB)
>       {
>         // ROS_ERROR("Cannot stream RGB and IR at the same time. Streaming RGB only.");
> ```

same comment as above, remove this comment, and potentially clean up the logic and not have a return

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/badgertechnologies/ros_astra_camera/1)*

**Comment by coxep** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[cfg/Astra.cfg, line 28 at r1](https://reviewable.io:443/reviews/badgertechnologies/ros_astra_camera/1#-L7_woYLhkpIgaz32azT:-L7aHioK4j_VtzazRU-_:b-eq5co4) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/da6ba422e86fa896497558d3788f246026bb5342/cfg/Astra.cfg#L28)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

The text string has no RGB option. If RGB is default, maybe it should be `"Override video type; 0=RGB(default), 1=IR"` ?
</blockquote></details>

This isn't actually an option, but a description (only seen when mousing over). But I agree, and actually thought I had made that change already...

---

*[src/astra_driver.cpp, line 402 at r1](https://reviewable.io:443/reviews/badgertechnologies/ros_astra_camera/1#-L7_yV2hDG7FklkaVSqp:-L7ql3T_4HaSgmZVFzJq:b-896fix) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/da6ba422e86fa896497558d3788f246026bb5342/src/astra_driver.cpp#L402)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

and simplifying logic, didn't finish my above statement. I can't finish the review this moment, I'll look at it more later.
</blockquote></details>

Done.

---

*[src/astra_driver.cpp, line 474 at r2](https://reviewable.io:443/reviews/badgertechnologies/ros_astra_camera/1#-L7aG43fErHWT7DdCsI3:-L7ql5KtG3WTp9Cb7hTV:b-896fix) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/874ec41afe4328d25ac3e8eced4de7b0c674612c/src/astra_driver.cpp#L474)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

same comment as above, remove this comment, and potentially clean up the logic and not have a return
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/badgertechnologies/ros_astra_camera/1)*

**Comment by c-andy-martin** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/badgertechnologies/ros_astra_camera/1#-:-L82h2XG-n1wZFMK18vh:bnfp4nl)*

**Comment by c-andy-martin** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/badgertechnologies/ros_astra_camera/1)*

**Comment by coxep** [comment]
@BadgerTechnologies/rosteam @cratliff please do not merge this yet

**Review by c-andy-martin — APPROVED** [review]

**Pull request merged**
