### PR TITLE
Add ability to use a lock file to coordinate camera bring up

### PR DESCRIPTION
**Pull request by bobhenz-jabil**
This is one part of several to get depthcams separated into their own (independent) systemd services.

This change is [Reviewable](https://reviewable.io/reviews/badgertechnologies/ros_astra_camera/2)

### CODE REVIEW

**Comment by c-andy-martin** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[src/astra_driver.cpp, line 39 at r1](https://beta.reviewable.io/reviews/badgertechnologies/ros_astra_camera/2#-L83HzjoCG1Ulq3IAHfQ:-L83Hzjp6tgWLSvVoUha:b6qgpr9) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/b00a8ff26908388b9474b086d104d7dd5458dcbe/src/astra_driver.cpp#L39)):*
> ```cpp
> #include <stdlib.h>  
> #include <stdio.h>  
> #include <sys/shm.h>
> ```

I would not change this line. Looks like your editor removed the two spaces here.

---

*[src/astra_driver.cpp, line 94 at r1](https://beta.reviewable.io/reviews/badgertechnologies/ros_astra_camera/2#-L83HsYHAs66NKefK7HC:-L83HsYHAs66NKefK7HD:blxzaij) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/b00a8ff26908388b9474b086d104d7dd5458dcbe/src/astra_driver.cpp#L94)):*
> ```cpp
>   }
>   else
>   {
> ```

This *might* all belong in MULTI_ASTRA, since it's only relevant when running multiple cameras. In fact, it seems like it would obsolete the old way of doing this.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/badgertechnologies/ros_astra_camera/2)*

**Comment by c-andy-martin** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/badgertechnologies/ros_astra_camera/2)*

**Comment by bobhenz-jabil** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/astra_driver.cpp, line 39 at r1](https://beta.reviewable.io/reviews/badgertechnologies/ros_astra_camera/2#-L83HzjoCG1Ulq3IAHfQ:-L83Khsn8WSA3lRh3rLc:b-896fix) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/b00a8ff26908388b9474b086d104d7dd5458dcbe/src/astra_driver.cpp#L39)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

I would not change this line. Looks like your editor removed the two spaces here.
</blockquote></details>

Done.

---

*[src/astra_driver.cpp, line 94 at r1](https://beta.reviewable.io/reviews/badgertechnologies/ros_astra_camera/2#-L83HsYHAs66NKefK7HC:-L83KgNF0W9nBmlpzn5s:b-896fix) ([raw file](https://github.com/badgertechnologies/ros_astra_camera/blob/b00a8ff26908388b9474b086d104d7dd5458dcbe/src/astra_driver.cpp#L94)):*
<details><summary><i>Previously, c-andy-martin (C. Andy Martin) wrote…</i></summary><blockquote>

This *might* all belong in MULTI_ASTRA, since it's only relevant when running multiple cameras. In fact, it seems like it would obsolete the old way of doing this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/badgertechnologies/ros_astra_camera/2)*

**Comment by c-andy-martin** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/badgertechnologies/ros_astra_camera/2)*

**Review by c-andy-martin — APPROVED** [review]

**Review by c-andy-martin — APPROVED** [review]

**Pull request merged**
